import mirrorCreator from 'mirror-creator';

const actionTypes = mirrorCreator([
  'OCCSN_BOOK_ORDER_REQUEST',
  'OCCSN_BOOK_ORDER_REQUEST_COMPLETE',
  'OCCSN_CONSTRUCT_ORDER_REQUEST',
  'OCCSN_FIND_REDEEMABLE_REQUEST',
  'OCCSN_FIND_REDEEMABLE_REQUEST_COMPLETE',
  'OCCSN_LOAD_PRODUCT_REQUEST',
  'OCCSN_SAVE_ORDER_REQUEST',
  'OCCSN_SAVE_ORDER_REQUEST_COMPLETE',
  'OCCSN_SET_ORDER',
  'OCCSN_SET_PRODUCT',
]);

export default actionTypes;
